services:
  - type: web
    name: memobox-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.backend.wsgi
    envVars:
      - key: PYTHONPATH
        value: .
